name: Build examples
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.1

    - name: pwd
      run: pwd

    - name: Install platform
      run: |
        pwd
        arduino-cli core update-index
        arduino-cli core install arduino:avr
        arduino-cli core install esp8266:esp8266
    
    - name: Build nodemcu
      run: |
        arduino-cli compile -b esp8266:esp8266:nodemcu

    - name: Build uno
      run: |
        arduino-cli compile -b arduino:avr:uno
    
