name: Build examples
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build all example sketches
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        board: "arduino:avr:leonardo"
        sketchDirectory: "smart-home-devices"
        sketch: "smart_home_devices.ino"