name: unit_test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install packages
        run: sudo apt-get install cmake

      - name: Create build dir 
        run: cd smart-home-devices && mkdir build && cd build

      - name: Build
        run: cmake .. && make

      - name: Run tests
        run: make test

    
