name: unit_test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install packages
        run: sudo apt-get install cmake

      - name: PWD
        run: |
          pwd
          ls -l
      
      - name: pwd a
        run: |
          pwd
          ls -l

      - name: Build
        run: cmake .

      - name: Run tests
        run: make test

    
